### ISSUE TITLE
Webpack integration 

### ISSUE THREAD

**Issue by kbytin** [Ser-Gen/postcss-data-packer#16]
I have a problem with Webpack integration. 

The plugin is working fine and generate new CSS file, but webpack doesn't inline it at the end.  If I disable the plugin, and trying to inline previously generated file - it is working.

So, I think webpack or postCSS config must be tweaked to have some delay or smth. Can you help with that?

**Comment by Ser-Gen** [comment]
Just to make it clear:
Are you want to inline `data.css` into your production bundle? It may slow page loading.
Maybe you need this for development build? Then you are not need to extract an embedded data, just `require` your usual css.

---

I don't know webpack very well, but I can suggest this way of inlining a generated file:

`webpack.config.js`

``` js
var dataPacker = require('postcss-data-packer');

module.exports = {
    entry: "./entry.js",
    output: { path: __dirname, filename: "bundle.js" },
    module: {
        loaders: [

            // to generate data-file
            {
                test: /[^\.data]\.css$/,
                loader: "style!css!postcss"
            },

            // to enable requiring of data-file
            {
                test: /\.data\.css$/,
                loader: "style!css"
            }
        ]
    },
    postcss: function () { return [
        dataPacker({
            dest: 'style.data.css'
        })
    ];}
};
```

`entry.js`

``` js
require("./style.css");
require("./style.data.css");
```

At first run webpack will return error because `style.data.css` is not ready.

```
ERROR in ./entry.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./style.data.css in test--webpack-data-packer-inline-result
 @ ./entry.js 2:0-27
```

Next compilations will run normally.
Am I understand your question correct?

**Comment by kbytin** [comment]
Thank You.  Code for " loaders:[ ]"   did the magic.   Working ok now
